/**
 * Session code util + auto-pair URL contract tests.
 *
 * Contract guarantee: the URL the plugin opens via `buildPairUrl` must be
 * parseable by the extension's background service worker (see
 * `packages/extension/src/background.ts` → `extractPairCode`). If either side
 * changes query param name, host, or code format, tests in this file catch it.
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import {
  generateSessionCode,
  isValidSessionCode,
  buildPairUrl,
  PAIR_QUERY_PARAM,
  SESSION_CODE_LENGTH,
  SESSION_CODE_PATTERN,
} from '../../src/utils/session-code';

const EXTENSION_BACKGROUND_SOURCE = fs.readFileSync(
  path.join(__dirname, '../../../extension/src/background.ts'),
  'utf8',
);

describe('session-code util', () => {
  describe('generateSessionCode', () => {
    it('produces a 6-char string', () => {
      for (let i = 0; i < 100; i++) {
        const code = generateSessionCode();
        expect(code).toHaveLength(SESSION_CODE_LENGTH);
      }
    });

    it('uses only A-Z 0-9 characters', () => {
      for (let i = 0; i < 100; i++) {
        const code = generateSessionCode();
        expect(code).toMatch(SESSION_CODE_PATTERN);
      }
    });

    it('is effectively random (high uniqueness across 1000 draws)', () => {
      const seen = new Set<string>();
      for (let i = 0; i < 1000; i++) seen.add(generateSessionCode());
      // With 36^6 = 2.17B possible codes, 1000 draws should be ~100% unique.
      // Allow a tiny margin for theoretical birthday-paradox collisions.
      expect(seen.size).toBeGreaterThan(998);
    });
  });

  describe('isValidSessionCode', () => {
    it('accepts valid 6-char A-Z 0-9 codes', () => {
      expect(isValidSessionCode('ABC123')).toBe(true);
      expect(isValidSessionCode('000000')).toBe(true);
      expect(isValidSessionCode('ZZZZZZ')).toBe(true);
    });

    it('rejects wrong length', () => {
      expect(isValidSessionCode('ABC12')).toBe(false);
      expect(isValidSessionCode('ABC1234')).toBe(false);
      expect(isValidSessionCode('')).toBe(false);
    });

    it('rejects lowercase', () => {
      expect(isValidSessionCode('abc123')).toBe(false);
    });

    it('rejects special chars / whitespace', () => {
      expect(isValidSessionCode('ABC-12')).toBe(false);
      expect(isValidSessionCode('ABC 12')).toBe(false);
      expect(isValidSessionCode('ABC/12')).toBe(false);
    });

    it('rejects non-strings', () => {
      expect(isValidSessionCode(null)).toBe(false);
      expect(isValidSessionCode(undefined)).toBe(false);
      expect(isValidSessionCode(123456)).toBe(false);
      expect(isValidSessionCode({})).toBe(false);
    });
  });

  describe('buildPairUrl', () => {
    it('produces a URL on ya.ru with the pair query param', () => {
      const url = new URL(buildPairUrl('ABC123'));
      expect(url.hostname).toBe('ya.ru');
      expect(url.searchParams.get(PAIR_QUERY_PARAM)).toBe('ABC123');
    });

    it('percent-encodes the code (though A-Z 0-9 have no reserved chars)', () => {
      // Safety belt: even if code format ever changes to allow reserved chars,
      // encodeURIComponent keeps the URL well-formed.
      const url = buildPairUrl('ABC123');
      expect(url).toBe('https://ya.ru/?contentify_pair=ABC123');
    });
  });
});

describe('auto-pair URL contract (plugin ↔ extension)', () => {
  it('extension uses the same PAIR_QUERY_PARAM name as the plugin', () => {
    // Plugin side of the contract is `PAIR_QUERY_PARAM` imported above.
    // Extension side hardcodes it as a string const in background.ts.
    expect(EXTENSION_BACKGROUND_SOURCE).toContain(`'${PAIR_QUERY_PARAM}'`);
  });

  it('extension accepts URLs on ya.ru / yandex.ru / yandex.com domains', () => {
    // Defence-in-depth host check — must mention the handshake host at minimum.
    expect(EXTENSION_BACKGROUND_SOURCE).toMatch(/ya\.ru/);
    expect(EXTENSION_BACKGROUND_SOURCE).toMatch(/yandex\.ru/);
  });

  it('extension validates the code against the same 6-char A-Z0-9 pattern', () => {
    // SESSION_CODE_PATTERN in extension/config.ts mirrors plugin side.
    // This contract test ensures the pattern source intent matches.
    expect(EXTENSION_BACKGROUND_SOURCE).toContain('SESSION_CODE_PATTERN');
  });

  it('a code generated by the plugin round-trips through extension-style parsing', () => {
    // Mirror of extension's extractPairCode — if this diverges from the real
    // parser, it means the contract shifted and we should fix the extension too.
    function extractPairCodeLikeExtension(urlString: string): string | null {
      let url: URL;
      try {
        url = new URL(urlString);
      } catch {
        return null;
      }
      const host = url.hostname;
      const isYandex =
        host === 'ya.ru' ||
        host.endsWith('.ya.ru') ||
        host === 'yandex.ru' ||
        host.endsWith('.yandex.ru') ||
        host === 'yandex.com' ||
        host.endsWith('.yandex.com');
      if (!isYandex) return null;
      const raw = url.searchParams.get(PAIR_QUERY_PARAM);
      return raw && SESSION_CODE_PATTERN.test(raw) ? raw : null;
    }

    const code = generateSessionCode();
    const url = buildPairUrl(code);
    expect(extractPairCodeLikeExtension(url)).toBe(code);
  });

  it('extension-style parser rejects non-Yandex hosts even with the pair param', () => {
    function extractPairCodeLikeExtension(urlString: string): string | null {
      let url: URL;
      try {
        url = new URL(urlString);
      } catch {
        return null;
      }
      const host = url.hostname;
      const isYandex =
        host === 'ya.ru' ||
        host.endsWith('.ya.ru') ||
        host === 'yandex.ru' ||
        host.endsWith('.yandex.ru');
      if (!isYandex) return null;
      const raw = url.searchParams.get(PAIR_QUERY_PARAM);
      return raw && SESSION_CODE_PATTERN.test(raw) ? raw : null;
    }

    expect(
      extractPairCodeLikeExtension('https://evil.example.com/?contentify_pair=ABC123'),
    ).toBeNull();
    expect(extractPairCodeLikeExtension('https://fake-ya.ru.evil/?contentify_pair=ABC123')).toBe(
      null,
    );
  });

  it('extension-style parser rejects malformed codes even on Yandex hosts', () => {
    function extractPairCodeLikeExtension(urlString: string): string | null {
      let url: URL;
      try {
        url = new URL(urlString);
      } catch {
        return null;
      }
      const host = url.hostname;
      if (host !== 'ya.ru') return null;
      const raw = url.searchParams.get(PAIR_QUERY_PARAM);
      return raw && SESSION_CODE_PATTERN.test(raw) ? raw : null;
    }

    expect(extractPairCodeLikeExtension('https://ya.ru/?contentify_pair=toolong12')).toBeNull();
    expect(extractPairCodeLikeExtension('https://ya.ru/?contentify_pair=abc123')).toBeNull();
    expect(extractPairCodeLikeExtension('https://ya.ru/?contentify_pair=')).toBeNull();
    expect(extractPairCodeLikeExtension('https://ya.ru/?other=ABC123')).toBeNull();
  });
});
