#!/usr/bin/env node
/**
 * Reads version from package.json and writes src/version.ts
 * so it gets baked into the pkg binary at compile time.
 */
const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));

const content = `// Auto-generated by scripts/generate-version.js — do not edit
export const RELAY_VERSION = '${pkg.version}';\n`;

const outPath = path.join(__dirname, '..', 'src', 'version.ts');
const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';

if (existing !== content) {
  fs.writeFileSync(outPath, content);
  console.log(`[generate-version] wrote ${pkg.version} → src/version.ts`);
} else {
  console.log(`[generate-version] src/version.ts already up to date (${pkg.version})`);
}
