import type { YcHttpEvent } from './types';

/**
 * Session IDs are 6-char uppercase alphanumerics generated by the plugin and
 * shared with the extension via a QR / paste flow. The handler uses this to
 * scope every row in YDB to a single user.
 */
const SESSION_RE = /^[A-Z0-9]{6}$/;

export function extractSessionId(event: YcHttpEvent): string | null {
  const query = event.queryStringParameters?.session ?? '';
  if (SESSION_RE.test(query)) return query;
  return null;
}
